diagExamples = [
    ["Barbara (1st figure)",
        [["new_all_some", "m", "p"], "prem", "All m are p"],
        [["new_all_some", "s", "m"], "prem", "All s are m"],
        [["conv",2,"m"]],
        [["inf",1,3]],
        [["conv",4,"s"]],
        [["ext", 5, "m"],"conc",  "All s are p"]],
	["Celarent (1st figure)",
	    [["new_all_some", "m", "¬p"], "prem", "No m is p"],
        [["new_all_some", "s", "m"], "prem", "All s are m"],
        [["conv",2,"m"]],
        [["inf",1,3]],
		[["conv",4,"s"]],
		[["ext",5, "m"], "conc", "No s is p"]],
    ["Darii (1st figure)",
        [["new_all_some",  "m", "p"], "prem", "All m are p"],
        [["new_some_some", "s", "m"], "prem", "Some s are m"],
        [["conv",2,"m"]],
        [["inf",1,3]],
        [["conv",4,"s"]],
        [["ext", 5, "m"], "conc", "Some s are p"]],
	["Ferio (1st figure)",
        [["new_all_some",  "m", "¬p"], "prem", "No m are p"],
        [["new_some_some", "s", "m"], "prem", "Some s are m"],
        [["conv",2,"m"]],
        [["inf",1,3]],
        [["conv",4,"s"]],
        [["ext", 5, "m"], "conc", "Some s are not p"]],
	["Cesare (2nd figure)",
        [["new_all_some",  "p", "¬m"], "prem", "No p are m"],
        [["new_all_some", "s", "m"],"prem", "All s are m"],
        [["trans",1]],
        [["conv",2,"m"]],
        [["inf",3,4]],
        [["conv",5,"s"]],
        [["ext", 6, "m"], "conc", "No s is p"]],
	["Camestres (2nd figure)",
        [["new_all_some",  "s", "m"], "prem", "All s are m"],
        [["new_all_some", "p", "¬m"],"prem", "No p is m"],
		[["trans",2]],
        [["conv",1,"m"]],
        [["inf",3,4]],
        [["conv",5,"s"]],
        [["ext", 6, "m"], "conc", "No s is p"]],
	["Festino (2nd figure)",
        [["new_all_some",  "p", "¬m"], "prem", "No p is m"],
        [["new_some_some", "s", "m"],"prem", "Some s are m"],
        [["trans",1]],
        [["conv",2,"m"]],
        [["inf",3,4]],
        [["conv",5,"s"]],
        [["ext", 6, "m"], "conc", "Some s are not p"]],
	["Baroco (2nd figure)",
        [["new_all_some",  "p", "m"], "prem", "All p are m"],
        [["new_some_some", "s", "¬m"],"prem", "Some s are not m"],
        [["trans",1]],
        [["conv",2,"¬m"]],
        [["inf",3,4]],
        [["conv",5,"s"]],
        [["ext", 6, "¬m"], "conc", "Some s are not p"]],
    ["Darapti (3rd figure)",
    	[["new_all_some", "m", "s"], "prem", "All m are s"],
    	[["new_all_some", "m", "p"], "prem", "All m are p"],
    	[["inf", 1, 2]],
    	[["conv", 3, "s"]],
	[["ext", 4, "m"], "conc", "Some s are p"]],
	["Disamis (3rd figure)",
    	[["new_some_some", "m", "p"], "prem", "All m are p"],
    	[["new_all_some", "m", "s"], "prem", "All m are s"],
    	[["inf", 1, 2]],
    	[["conv", 3, "s"]],
	    [["ext", 4, "m"], "conc", "Some s are p"]],
	["Datisi (3rd figure)",
    	[["new_all_some", "m", "p"], "prem", "All m are p"],
    	[["new_some_some", "m", "s"], "prem", "Some m are s"],
    	[["inf", 1, 2]],
    	[["conv", 3, "s"]],
	    [["ext", 4, "m"], "conc", "Some s are p"]],
	["Felapton (3rd figure)",
    	[["new_all_some", "m", "¬p"], "prem", "No m is p"],
    	[["new_all_some", "m", "s"], "prem", "Some m are s"],
    	[["inf", 1, 2]],
    	[["conv", 3, "s"]],
	    [["ext", 4, "m"], "conc", "Some s are not p"]],
	["Ferison (3rd figure)",
    	[["new_all_some", "m", "¬p"], "prem", "No m is p"],
    	[["new_some_some", "m", "s"], "prem", "Some m are s"],
    	[["inf", 1, 2]],
    	[["conv", 3, "s"]],
	    [["ext", 4, "m"], "conc", "Some s are not p"]],
    ["Bocardo (3rd figure)",
    	[["new_some_some", "m", "¬p"], "prem", "Some m are not p"],
    	[["new_all_some", "m", "s"], "prem", "All m are s"],
    	[["inf", 1, 2]],
    	[["conv", 3, "s"]],
	    [["ext", 4, "m"], "conc", "Some s are not p"]],
    ["Bamalip (4st figure)",
        [["new_all_some", "p", "m"], "prem", "All p are m"],
        [["new_all_some", "m", "s"], "prem", "All m are s"],
        [["conv",1,"m"]],
        [["inf",2,3]],
        [["conv",4,"s"]],
        [["ext", 5, "m"],"conc",  "some s are p"]],
	["Camenes (4st figure)",
        [["new_all_some", "s", "m"], "prem", "All s are m"],
        [["new_all_some", "m", "¬p"], "prem", "No m is p"],
        [["conv",1,"m"]],
        [["inf",2,3]],
        [["conv",4,"s"]],
        [["ext", 5, "m"],"conc",  "No s are p"]],
	["Dimaris (4st figure)",
        [["new_some_some", "s", "m"], "prem", "Some s are m"],
        [["new_all_some", "m", "p"], "prem", "All m are p"],
        [["conv",1,"m"]],
        [["inf",2,3]],
        [["conv",4,"s"]],
        [["ext", 5, "m"],"conc",  "Some s are p"]],
	["Fresison (4st figure)",
        [["new_all_some", "p", "¬m"], "prem", "No p is m"],
        [["new_some_some", "m", "s"], "prem", "Some m are s"],
        [["trans",1]],
        [["inf",2,3]],
        [["conv",4,"s"]],
        [["ext", 5, "m"],"conc",  "Some s are not p"]],
	["Fesapo (4st figure)",
        [["new_all_some", "p", "¬m"], "prem", "No p is m"],
        [["new_all_some", "m", "s"], "prem", "All m are s"],
        [["trans",1]],
        [["inf",2,3]],
        [["conv",4,"s"]],
        [["ext", 5, "m"],"conc",  "Some s are not p"]],
	["Disjunction Elimination",
        [["new_all_some", "p", "q"], "prem", "If p then q"],
        [["new_all_some", "r", "q"], "prem", "If r then q"],
		[["new_all_some", "¬r", "p"], "prem", "r or p"],
		[["conv",3,"p"]],
        [["inf",1,4]],
		[["conv",5,"q"]],
		[["ext",6, "p"]],
		[["conv",2,"q"]],
		[["inf",7,8], "conc",  "It is only possible q"]],
	["Constructive dilemma",
        [["new_all_some", "p", "q"], "prem", "If p then q"],
        [["new_all_some", "r", "s"], "prem", "If r then s"],
		[["new_all_some", "¬p", "r"], "prem", "p or r"],
		[["trans",1]],
        [["conv",4,"¬p"]],
		[["inf",3,5]],
		[["conv",6,"r"]],
		[["ext",7,"¬p"]],
		[["inf",2,8]],
		[["conv",9,"¬q"]],
		[["ext",10, "r"], "conc",  "q or s"]],
	["Bicondicitional Introduction",
        [["new_all_some", "p", "q"], "prem", "If p then q"],
        [["new_all_some", "q", "p"], "prem", "If q then p"],
		[["conv",1,"q"]],
        [["inf",2,3], "conc", "Iff q then p"]]		
    ];
